# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

[pytest]
# Run the suite across all available cores. Pass `-n0` to disable, which is
# needed when benchmarking or debugging an individual test.
addopts = -n auto
usefixtures = fresh_global_config
markers =
    no_mock_token
